language: node_js
nodejs:
  - 14

script:
  - yarn lint && yarn typecheck

after_success:
  - yarn build:doc

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      branch: master
#       tags: true
#   - provider: releases
#     api_key: $GITHUB_TOKEN
#     file_glob: true
#     file: "{YOURLIB}-*.tgz"
#     skip_cleanup: true
#     on:
#       tags: true
#   - provider: npm
#     skip_cleanup: true
#     email: "youremail@example.com"
#     api_key: $NPM_TOKEN
#     on:
#       tags: true